version: '3.6'

services:
  backend:
        image: npetersdev/spring-petclinic-rest:test
        ports:
         - '9966:9966'

  angular:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - backend

  cypress:
    build:
      context: .
      dockerfile: Dockerfile-Cypress
    depends_on:
      - angular
    network_mode: 'host'