# base image
FROM cypress/browsers:latest

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# install cypress
RUN npm install cypress

# copy cypress files and folders
COPY cypress /usr/src/app/cypress
COPY cypress.json /usr/src/app/cypress.json
COPY package.json /usr/src/app/package.json
RUN npm install
RUN npm i @cypress/webpack-preprocessor 
RUN npm i ts-loader
# confirm the cypress install

RUN npx cypress verify
        